name: Create Release with Zip File

on:
  release:
    types: [published]

jobs:
  build:
    name: Create Zip File
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip entire repository
      run: |
        zip -r st_libs.zip . -x ".git/*"

    - name: Upload st_libs.zip to Release
      uses: actions/upload-st_libs-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./st_libs.zip
        asset_name: st_libs.zip
        asset_content_type: application/zip